trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  resourceGroupName: codingassessment
  dataFactoryName: datalakeassessment
  location: 'Central India'  

stages:
- stage: DeployADF
  jobs:
  - job: Deploy
    steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'azure-rg-codingassessment'
    subscriptionId: '9b3e5533-a1b4-494a-abc5-9f0041edd6c4'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(armTemplateFile)'
    csmParametersFile: '$(armTemplateParametersFile)'
    deploymentMode: 'Incremental'
